from __future__ import annotations

import copy
import json
import unittest
from pathlib import Path

from scripts.verify_adversarial_fixtures import DEFAULT_FIXTURES, audit_case, verify_document


class AdversarialFleetFixturesTest(unittest.TestCase):
    def setUp(self) -> None:
        self.document = json.loads(Path(DEFAULT_FIXTURES).read_text(encoding="utf-8"))

    def test_checked_in_fixtures_are_all_detected_exactly(self) -> None:
        self.assertEqual(verify_document(self.document), [])

    def test_auditor_does_not_mutate_input(self) -> None:
        case = copy.deepcopy(self.document["cases"][0])
        before = copy.deepcopy(case)
        audit_case(case)
        self.assertEqual(case, before)

    def test_exact_generated_marker_allows_owned_regeneration(self) -> None:
        clean = {
            "kind": "generated-ownership",
            "input": {
                "operation": "overwrite",
                "expected_marker": "// @generated by ores-stack",
                "observed_marker": "// @generated by ores-stack",
                "target_kind": "regular-file",
            },
        }
        self.assertEqual(audit_case(clean), [])

    def test_complete_cache_key_and_matching_binary_are_clean(self) -> None:
        key = {
            "kind": "cache-key",
            "input": {
                "required": ["schema", "transport", "abi", "toolchain"],
                "present": ["schema", "transport", "abi", "toolchain"],
            },
        }
        entry = {
            "kind": "cache-entry",
            "input": {
                "receipt_regular": True,
                "binary_regular": True,
                "expected_build_sha256": "a" * 64,
                "receipt_build_sha256": "a" * 64,
                "receipt_binary_sha256": "b" * 64,
                "observed_binary_sha256": "b" * 64,
            },
        }
        self.assertEqual(audit_case(key), [])
        self.assertEqual(audit_case(entry), [])

    def test_pinned_confined_plugin_execution_is_clean(self) -> None:
        clean = {
            "kind": "plugin-exec",
            "input": {
                "executable": "/opt/ores/plugins/example",
                "resolved": "/opt/ores/plugins/example",
                "approved_roots": ["/opt/ores/plugins"],
                "expected_sha256": "d" * 64,
                "observed_sha256": "d" * 64,
                "shell": False,
                "cwd": "/workspace/project/generated-staging",
                "admitted_root": "/workspace/project",
                "inherited_control_env": [],
            },
        }
        self.assertEqual(audit_case(clean), [])

    def test_zero_step_pass_is_rejected_but_real_pass_is_not(self) -> None:
        planted = {"kind": "evidence", "input": {"state": "passed", "executed_steps": 0}}
        clean = {"kind": "evidence", "input": {"state": "passed", "executed_steps": 7}}
        self.assertEqual(audit_case(planted), ["fleet.evidence.zero-step-pass"])
        self.assertEqual(audit_case(clean), [])


if __name__ == "__main__":
    unittest.main()
