from __future__ import annotations

import copy
import os
import tempfile
import unittest
from pathlib import Path

from scripts.verify_ores_stack_cli_integrity import (
    PLUGIN_PROTOCOL,
    build_cache_key,
    load_contract,
    regeneration_decision,
    sha256_bytes,
    validate_plugin_command,
    verify_cache_entry,
    verify_contract,
)


def digest(label: str) -> str:
    return sha256_bytes(label.encode("utf-8"))


def cache_spec(project: str = "alpha") -> dict:
    return {
        "project_identity": project,
        "source_digests": {
            "src/main.rs": digest("main"),
            "src/lib.rs": digest("lib"),
        },
        "lockfile_digest": digest("Cargo.lock"),
        "compiler_identity": "rustc 1.88.0 (stable-x86_64-unknown-linux-gnu)",
        "generator_identity": "ores-stack@0123456789abcdef0123456789abcdef01234567",
        "target_identity": "x86_64-unknown-linux-gnu",
        "feature_flags": ["http", "rpc"],
        "contract_digests": {
            "module-semantics": digest("module-contract"),
            "route-map": digest("route-map"),
        },
    }


class OresStackCliIntegrityTest(unittest.TestCase):
    def test_checked_in_contract_is_coherent(self) -> None:
        self.assertEqual(verify_contract(load_contract()), [])

    def test_regeneration_preserves_user_owned_file(self) -> None:
        self.assertEqual(
            regeneration_decision(
                current_bytes=b"pub fn user_code() {}\n",
                desired_bytes=b"generated\n",
                generated_marker=b"// @generated",
                last_published_sha256=None,
            ),
            "reject-user-owned",
        )

    def test_regeneration_rejects_modified_generated_file(self) -> None:
        original = b"// @generated by ores-stack\nold\n"
        edited = b"// @generated by ores-stack\nmanual edit\n"
        self.assertEqual(
            regeneration_decision(
                current_bytes=edited,
                desired_bytes=b"// @generated by ores-stack\nnew\n",
                generated_marker=b"// @generated by ores-stack",
                last_published_sha256=sha256_bytes(original),
            ),
            "reject-modified-generated",
        )

    def test_regeneration_allows_reconciled_generated_replacement(self) -> None:
        current = b"// @generated by ores-stack\nold\n"
        self.assertEqual(
            regeneration_decision(
                current_bytes=current,
                desired_bytes=b"// @generated by ores-stack\nnew\n",
                generated_marker=b"// @generated by ores-stack",
                last_published_sha256=sha256_bytes(current),
            ),
            "publish",
        )

    def test_cache_key_changes_for_every_required_identity_dimension(self) -> None:
        baseline = cache_spec()
        baseline_key = build_cache_key(baseline)
        mutations = []

        changed = copy.deepcopy(baseline)
        changed["project_identity"] = "beta"
        mutations.append(changed)

        changed = copy.deepcopy(baseline)
        changed["source_digests"]["src/main.rs"] = digest("changed-source")
        mutations.append(changed)

        changed = copy.deepcopy(baseline)
        changed["lockfile_digest"] = digest("changed-lock")
        mutations.append(changed)

        changed = copy.deepcopy(baseline)
        changed["compiler_identity"] = "rustc 1.89.0"
        mutations.append(changed)

        changed = copy.deepcopy(baseline)
        changed["generator_identity"] = "ores-stack@fedcba9876543210fedcba9876543210fedcba98"
        mutations.append(changed)

        changed = copy.deepcopy(baseline)
        changed["target_identity"] = "aarch64-unknown-linux-gnu"
        mutations.append(changed)

        changed = copy.deepcopy(baseline)
        changed["feature_flags"] = ["http"]
        mutations.append(changed)

        changed = copy.deepcopy(baseline)
        changed["contract_digests"]["route-map"] = digest("changed-contract")
        mutations.append(changed)

        for item in mutations:
            self.assertNotEqual(build_cache_key(item), baseline_key)

    def test_cache_key_is_order_independent_for_sets_and_maps(self) -> None:
        first = cache_spec()
        second = copy.deepcopy(first)
        second["feature_flags"] = list(reversed(second["feature_flags"]))
        second["source_digests"] = dict(reversed(list(second["source_digests"].items())))
        second["contract_digests"] = dict(reversed(list(second["contract_digests"].items())))
        self.assertEqual(build_cache_key(first), build_cache_key(second))

    def test_substituted_binary_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            artifact = root / "bin" / "leaf"
            artifact.parent.mkdir()
            artifact.write_bytes(b"substituted")
            expected_key = build_cache_key(cache_spec())
            entry = {
                "schema": "ores.stack.build-cache-entry/v1",
                "project_identity": "alpha",
                "cache_key": expected_key,
                "artifact": {
                    "path": "bin/leaf",
                    "sha256": sha256_bytes(b"original"),
                    "size_bytes": len(b"substituted"),
                },
            }
            self.assertIn(
                "cache.digest-mismatch",
                verify_cache_entry(
                    entry,
                    artifact_root=root,
                    expected_project_identity="alpha",
                    expected_cache_key=expected_key,
                ),
            )

    def test_cross_project_cache_collision_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            artifact = root / "leaf"
            artifact.write_bytes(b"ok")
            expected_key = build_cache_key(cache_spec("alpha"))
            entry = {
                "schema": "ores.stack.build-cache-entry/v1",
                "project_identity": "beta",
                "cache_key": expected_key,
                "artifact": {
                    "path": "leaf",
                    "sha256": sha256_bytes(b"ok"),
                    "size_bytes": 2,
                },
            }
            self.assertIn(
                "cache.cross-project-collision",
                verify_cache_entry(
                    entry,
                    artifact_root=root,
                    expected_project_identity="alpha",
                    expected_cache_key=expected_key,
                ),
            )

    @unittest.skipUnless(hasattr(os, "symlink"), "symlink support required")
    def test_symlink_cache_artifact_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            outside = root / "outside"
            outside.write_bytes(b"ok")
            link = root / "leaf"
            os.symlink(outside, link)
            expected_key = build_cache_key(cache_spec())
            entry = {
                "schema": "ores.stack.build-cache-entry/v1",
                "project_identity": "alpha",
                "cache_key": expected_key,
                "artifact": {
                    "path": "leaf",
                    "sha256": sha256_bytes(b"ok"),
                    "size_bytes": 2,
                },
            }
            self.assertIn(
                "cache.artifact-not-regular",
                verify_cache_entry(
                    entry,
                    artifact_root=root,
                    expected_project_identity="alpha",
                    expected_cache_key=expected_key,
                ),
            )

    def test_plugin_requires_declared_path_argv_allowlist_and_compatibility(self) -> None:
        valid = {
            "schema": PLUGIN_PROTOCOL,
            "executable": {"root": "toolchain", "path": "bin/example-plugin"},
            "argv": ["check", "--json"],
            "environment_allowlist": ["HOME", "TMPDIR"],
            "working_directory": {"root": "project", "path": "."},
            "compatibility": {
                "protocol": PLUGIN_PROTOCOL,
                "min_cli_version": "0.1.0",
                "max_cli_version": "0.1.9",
            },
        }
        self.assertEqual(validate_plugin_command(valid), [])

        bare = copy.deepcopy(valid)
        bare["executable"] = {"root": "toolchain", "path": "../example-plugin"}
        self.assertIn("plugin.executable-path", validate_plugin_command(bare))

        shell_string = copy.deepcopy(valid)
        shell_string["argv"] = "check && curl example.invalid"
        self.assertIn("plugin.argv-array", validate_plugin_command(shell_string))

        wildcard_env = copy.deepcopy(valid)
        wildcard_env["environment_allowlist"] = ["*"]
        self.assertIn("plugin.environment-allowlist", validate_plugin_command(wildcard_env))

        missing_compat = copy.deepcopy(valid)
        missing_compat.pop("compatibility")
        self.assertIn("plugin.compatibility", validate_plugin_command(missing_compat))


if __name__ == "__main__":
    unittest.main()
