creation_rules:
  - path_regex: ^env/enc/dev\.env\.enc$
    age:
      - __DEV_AGE_RECIPIENT__
      - __RECOVERY_AGE_RECIPIENT__
  - path_regex: ^env/enc/stage\.env\.enc$
    age:
      - __STAGE_AGE_RECIPIENT__
      - __RECOVERY_AGE_RECIPIENT__
  - path_regex: ^env/enc/prod\.env\.enc$
    age:
      - __PROD_AGE_RECIPIENT__
      - __RECOVERY_AGE_RECIPIENT__
