[package]
org = "oresoftware"
name = "comparison-ores-stack-http-observability"
version = "0.1.0"
language = "rust"
[dependencies]
"oresoftware/ores-compose" = "=0.1.0"
"oresoftware/typespec-json-schema-validator" = "=0.1.1"
"oresoftware/ores-stack" = "=0.1.0"
[targets.contracts]
dir = "contracts"
name = "comparison-contracts"
adapter = "none"
[targets.conformance]
dir = "conformance"
name = "comparison-conformance"
adapter = "none"
