[package]
name = "scintilla-module-interface-cli-cert"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ores-api-docs = { git = "https://github.com/ORESoftware/api-docs.git", rev = "c02712957850046e339b1e94d8d41b219feb304c", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
